name: Benchmark Bundlers

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install --frozen-lockfile

      - run: mkdir -p time

      - name: Run all bundler benchmarks
        shell: bash
        run: |
          run_benchmark() {
            SCRIPT=$1
            LOG=$2

            # Parcel needs "source": "index.html"
            if [[ "$SCRIPT" == "build:parcel" ]]; then
              echo "Adding Parcel source field to package.json"
              jq '. + {source: "index.html"}' package.json > package.tmp.json
              mv package.tmp.json package.json
            fi

            for i in {1..10}; do
              echo "Run #$i" >> "time/$LOG.log"

              /usr/bin/time -v yarn $SCRIPT 2>&1 | awk '
                /Maximum resident set size/ {ram=$6/1024}
                /Percent of CPU this job got/ {cpu=$0; sub(/.*: /,"",cpu)}
                END {printf "Peak RAM: %.2f MB\nCPU Load: %s\n", ram, cpu}' \
                >> "time/$LOG.log"
            done
          }

          run_benchmark build:esbuild esbuild
          run_benchmark build:rollup rollup
          run_benchmark build:webpack webpack
          run_benchmark build:farm farm
          run_benchmark build:rspack rspack
          run_benchmark build:parcel parcel
          run_benchmark build:snowpack snowpack
          run_benchmark build:rolldown rolldown

          cd my-app 
          yarn install --frozen-lockfile 
          yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./,next   # or .next if using next export


  deploy:
    needs: benchmark
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
